=== openmhealth/schemas/schema/omh/calories-burned-3.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://w3id.org/openmhealth/schemas/omh/calories-burned-3.0.json",
    "description": "This schema represents the amount of calories burned in kilocalories (kcal).",
    "type": "object",

    "references": [
        {
            "description": "The LOINC code represents Calories burned:Power = Energy/Time:Point in time:^Patient:Quantitative, that is, a Quantitative measure of Calories burned by a Patient at a Point in time",
            "url": "http://purl.bioontology.org/ontology/LNC/41981-2"
        }
    ],

    "definitions": {
        "kcal_unit_value": {
            "$ref": "https://w3id.org/ieee/ieee-1752-schema/kcal-unit-value-1.0.json"
        },
        "time_frame": {
            "$ref": "https://w3id.org/ieee/ieee-1752-schema/time-frame-1.0.json"
        },
        "activity_name": {
            "$ref": "activity-name-1.x.json"
        },
        "descriptive_statistic": {
            "$ref": "https://w3id.org/ieee/ieee-1752-schema/descriptive-statistic-1.0.json"
        },
        "descriptive_statistic_denominator": {
            "$ref": "https://w3id.org/ieee/ieee-1752-schema/descriptive-statistic-denominator-1.0.json"
        }
    },

    "properties": {
        "kcal_burned": {
            "$ref": "#/definitions/kcal_unit_value"
        },
        "activity_name": {
            "$ref": "#/definitions/activity_name"
        },
        "effective_time_frame": {
            "description": "As a measure of a phenomenon that occurs over a period of time, calories burned should not be associated to a date time time frame. Hence, effective time frame is restricted to be a time interval.",
            "allOf": [
                {
                    "$ref": "#/definitions/time_frame"
                },
                {
                    "required": ["time_interval"]
                }
            ]
        },
        "descriptive_statistic": {
            "$ref": "#/definitions/descriptive_statistic"
        },
        "descriptive_statistic_denominator": {
            "anyOf": [
                {
                    "$ref": "#/definitions/descriptive_statistic_denominator"
                },
                {
                    "description": "If the value needed is a standard unit of duration, select from the duration-unit-value value set.",
                    "type": "string"
                }
            ]
        }
    },

    "required": [
        "kcal_burned",
        "effective_time_frame"
    ]
}

=== openmhealth/schemas/test-data/omh/calories-burned/3.0/shouldPass/with-descriptive-statistic.json
{
    "kcal_burned": {
        "value": 1635,
        "unit": "kcal"
    },
    "effective_time_frame": {
        "time_interval": {
            "start_date_time": "2026-02-05T07:00:00Z",
            "end_date_time": "2023-06-06T07:00:00Z"
        }
    },
    "descriptive_statistic": "average",
    "descriptive_statistic_denominator": "d"
}
