=== openmhealth/schemas/schema/omh/orientation-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "description": "This schema represents gyroscope measurements. The assumption is a 2-axis gyroscope. For a 3-axis gyroscope, the z measurement should also be required.",
    "type": "object",

    "definitions": {
        "angular_velocity_unit_value": {
            "$ref": "angular-velocity-unit-value-1.x.json"
        },
        "time_frame": {
            "$ref": "time-frame-1.x.json"
        },
        "body_location": {
            "$ref": "body-location-1.x.json"
        },
        "descriptive_statistic": {
            "$ref": "descriptive-statistic-1.x.json"
        }
    },

    "properties": {
        "angular_velocity_x": {
            "$ref": "#/definitions/angular_velocity_unit_value"
        },
        "angular_velocity_y": {
            "$ref": "#/definitions/angular_velocity_unit_value"
        },
        "angular_velocity_z": {
            "$ref": "#/definitions/angular_velocity_unit_value"
        },
        "effective_time_frame": {
            "$ref": "#/definitions/time_frame"
        },
        "sensor_body_location": {
            "$ref": "#/definitions/body_location"
        },
        "descriptive_statistic": {
            "$ref": "#/definitions/descriptive_statistic"
        }
    },
    "required": [
        "angular_velocity_x",
        "angular_velocity_y",
        "effective_time_frame"
    ]
}

=== openmhealth/schemas/test-data/omh/orientation/2.0/shouldPass/valid-orientation.json
{
    "angular_velocity_x": {
        "value": 0.0596923828125,
        "unit": "rad/s"
    },
    "angular_velocity_y": {
        "value": 0.0125,
        "unit": "rad/s"
    },
    "angular_velocity_z": {
        "value": 0.0001,
        "unit": "rad/s"
    },
    "sensor_body_location": "right wrist",
    "effective_time_frame": {
        "date_time": "2025-08-18T07:25:00Z"
    }
}
