=== openmhealth/schemas/schema/omh/pharmacy-medication-dispensing-3.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://w3id.org/openmhealth/schemas/omh/pharmacy-medication-dispensing-3.0.json",
    "description": "This schema represents the dispensing by a pharmacy of medication based on a prescription e.g., atenolol 50 mg, 20 tab.",

    "type": "object",

    "definitions": {
        "medication_prescription": {
            "$ref": "medication-prescription-3.x.json"
        },
        "time_frame": {
            "$ref": "https://w3id.org/ieee/ieee-1752-schema/time-frame-1.0.json"
        }
    },

    "properties": {
        "medication_prescription": {
            "$ref": "#/definitions/medication_prescription"
        },
        "medication_dispensed": {
            "description": "NDC code of the medication dispensed by the pharmacy, e.g., 10882-527-07, where 10882-527 indicates the medication and 07 the package size",
            "type": "string"
        },
        "amount_dispensed": {
            "allOf": [
                {
                    "$ref": "https://w3id.org/ieee/ieee-1752-schema/unit-value-1.0.json"
                },
                {
                    "properties": {
                        "unit": {
                            "description": "The list of most commonly used units of measure for a medication dispensed. Suggestions for additions are accepted.",
                            "references": [
                                {
                                    "description": "Units are drawn in part from FDA units of presentation.",
                                    "url": "http://www.fda.gov/ForIndustry/DataStandards/StructuredProductLabeling/ucm162049.htm"
                                },
                                {
                                    "description": "Units are drawn in part from FDA pharmaceutical dosage form.",
                                    "url": "http://www.fda.gov/ForIndustry/DataStandards/StructuredProductLabeling/ucm162038.htm"
                                }
                            ],
                            "enum": [
                                "ampule",
                                "applicator",
                                "bag",
                                "bar",
                                "bead",
                                "blister",
                                "bottle",
                                "box",
                                "can",
                                "canister",
                                "capsule",
                                "carton",
                                "cartridge",
                                "cellular sheet",
                                "cloth",
                                "container",
                                "cup",
                                "cylinder",
                                "disc",
                                "dose pack",
                                "globule",
                                "granule",
                                "gum",
                                "inhaler",
                                "jar",
                                "jug",
                                "kit",
                                "lozenge",
                                "package",
                                "packet",
                                "pastille",
                                "patch",
                                "pellet",
                                "piece",
                                "pill",
                                "pouch",
                                "ring",
                                "salve",
                                "stick",
                                "strip",
                                "suppository",
                                "swab",
                                "syringe",
                                "tablet",
                                "tampon",
                                "tape",
                                "troche",
                                "tube",
                                "vial",
                                "wafer"
                            ]
                        }
                    }
                }
            ]
        },
        "time_frame_medication_dispensed": {
            "$ref": "#/definitions/time_frame"
        },
        "remaining_refills": {
            "description": "The number of refills still available in the prescription.",
            "type": "number"
        }
    },
    "required": [
        "medication_prescription",
        "medication_dispensed",
        "amount_dispensed",
        "time_frame_medication_dispensed"
    ]
}

=== openmhealth/schemas/test-data/omh/pharmacy-medication-dispensing/3.0/shouldPass/valid-medication-dispensed.json
{
    "medication_prescription": {
        "description": "Ascriptin 500 mg 1 tab every 6 hours for 2 weeks",

        "medication": {
            "generic_name": "Ascriptin",
            "strength": [
                {
                    "value": 500,
                    "unit": "mg"
                }
            ],
            "rxnorm_code": 830525
        },

        "route": "oral",

        "schedule": [
            {
                "dose_duration": {
                    "duration": {
                        "value": 2,
                        "unit": "wk"
                    }
                },
                "medication_dose": {
                    "dose": {
                        "value": 1,
                        "unit": "tablet"
                    }
                },
                "dose_recurrence": {
                    "number_of_times": 1,
                    "time_window": {
                        "value": 6,
                        "unit": "h"
                    }
                }
            }
        ]
    },
    "medication_dispensed": "0067-0143-85",

    "time_frame_medication_dispensed": {
        "date_time": "2026-02-05T17:25:00.123Z"
    },
    "amount_dispensed": {
        "value": 56,
        "unit": "tablet"
    }
}
